#!/bin/sh

check_aliases_config() {
  var_name="LI_${language}_alias"
  binary_name=${!var_name}
}

usage() {
  cat <<-EOF
USAGE:

lang_install help
    Show usage
lang_install list
    List installed languages
lang_install add [OPTIONS] LANGUAGE [VERSION]
    Install a new language / version 
lang_install remove [OPTIONS] LANGUAGE [VERSION]
    Remove an installed language

OPTIONS
  -a, --alpine
        Use alpine images
  -b <BINARY_NAME>, --binary <BINARY_NAME>
        Specify the main binary name. Default is equal to the language's name, can be configured in config/.config_aliases
  -d, --debug
      Debug mode. Show what binaries whould be installed
  -v, --verbose
      Show more logs
EOF
  exit 0
}

list() {
  tree -d $LI_DOCKER_PATH_BINS
  exit 0
}

help() {
  usage
}

error() {
  echo $1 >&2
  exit 1
}

confirm() {
  read -p "$1 ? [YyNn]" -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    return 0
  fi
  exit 0
}

add_lang() {
  [[ -z $binary_name ]] && check_aliases_config
  : ${binary_name:=$language}

  build_file_name="build${use_alpine:+_alpine}.sh"
  if [[ -f "languages/$language/$build_file_name" ]]; then
    build_file_path="languages/$language/$build_file_name"
  elif [[ -f "languages/default/$build_file_name" ]]; then
    build_file_path="languages/default/$build_file_name"
  else
    error "Error: Build file $build_file_name not found"
  fi

  dockerfile_name="Dockerfile${use_alpine:+.alpine}"
  if [[ -f "languages/$language/$dockerfile_name" ]]; then
    dockerfile_path="languages/$language/$dockerfile_name"
  elif [[ -f "languages/default/$dockerfile_name" ]]; then
    dockerfile_path="languages/default/$dockerfile_name"
  else
    error "Error: Build file $dockerfile_name not found"
  fi

  : ${debug:=false}
  : ${verbose:=false}

  ./$build_file_path $language $version $binary_name $dockerfile_path $debug $verbose
  docker image prune -f
}

remove_lang() {
  if [[ $version != 'latest' ]]; then
    if [[ -d "bin/$language/$version" ]]; then
      confirm "Remove $language version $version"
      rm -r bin/$language/$version
      echo "$language version $version is removed"
    else
      error "Error: $language version $version is not installed"
    fi
  else
    if [[ -d "bin/$language" ]]; then
      confirm "Remove $language"
      rm -r bin/$language
      echo "$language is removed"
    else
      error "Error: $language is not installed"
    fi
  fi

  # if multiple versions
  #   remove the specified version
  # else
  #   remove the folder
}

project_dir=$(realpath $0 | xargs dirname)
cd $project_dir

. ./scripts/load_config.sh
. scripts/parse_yaml.sh
eval $(parse_yaml $PWD/config/.config.yaml "LI_")

# Parse action
[[ $# -eq 0 ]] && usage
case $1 in
  add|remove) action=$1; shift;;
  list|help) $1;;
  *) usage;;
esac

# Parse options
[[ $# -eq 0 ]] && error "Error: Language is missing"
while (( "$#" )); do
  [[ $1 =~ ^-a|--alpine$ ]] && { use_alpine=true; shift; continue; };
  [[ $1 =~ ^-b|--binary$ ]] && {
    if [[ -n $2 ]] && [[ ${2:0:1} != "-" ]]; then
      binary_name=$2; shift 2; continue;
    else
      error "Error: Argument for $1 is missing"
    fi
  };
  [[ $1 =~ ^-d|--debug$ ]] && { debug=true; shift; continue; };
  [[ $1 =~ ^-v|--verbose$ ]] && { verbose=true; shift; continue; };
  [[ ${1:0:1} == '-' ]] && error "Error: Unknown param $1"
  [[ -z $1 ]] && error "Error: Language is missing"
  language=$1
  version=$([[ -n $2 ]] && echo $2 || echo 'latest')
  break
done
[[ -z $language ]] && error "Error: Language is missing"

[[ $action == 'add' ]] && add_lang
[[ $action == 'remove' ]] && remove_lang
./scripts/refresh_env_file.sh
