#!/bin/sh

project_dir=$(realpath $0 | xargs dirname)
cd $project_dir

. lib/parse_options.sh
. lib/utils.sh
. lib/actions.sh
. lib/load_config.sh

. scripts/load_config.sh
. scripts/parse_yaml.sh

parse_options "${@}"

[[ $action == 'add' ]] && add_lang
[[ $action == 'remove' ]] && remove_lang
./scripts/refresh_env_file.sh