# Global

# Ruby
ruby:
  env:
    gem_path: $HOME/.gems
    gem_home: $HOME/.gems
    bundle_path: $HOME/.gems
  export_env: RAILS_ENV
  volume:
    name: li_ruby_gems

# Node
node:
  volume:
    name: li_node
  additional_packages:
    default: git
    alpine: git

# Postgres
postgres:
  alias: psql

# Golang
golang:
  alias: go
